using DeviceService.Domain.Primitives;

namespace DeviceService.Domain.Entities;

public class EnergyRecord : Entity
{
    public Guid UserId { get; set; } // User associated with the energy record
    public float EnergyGeneratedKWh { get; set; } // Energy generated by all user generators in kWh
    public float EnergyConsumedKWh { get; set; } // Energy consumed by all user devices in kWh
    public float EnergyBalanceKWh { get; set; } // Energy balance in kWh (generated - consumed)
    public DateOnly Date { get; set; } // Date of the energy record
}
